---
name: geode

releases:
- name: geode
  version: latest
  #url: git+https://github.com/eitansuez/geode-release

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: locator
  azs: [z1,z2,z3]
  instances: 2
  jobs:
  - name: locator
    release: geode
  vm_type: default
  stemcell: default
  networks:
  - name: default

- name: cacheserver
  azs: [z1,z2,z3]
  instances: 3
  jobs:
  - name: cacheserver
    release: geode
  vm_type: default
  stemcell: default
  networks:
  - name: default
